version: '3'
services:

  app:
    build: ./app
    container_name: app
    # ports:
    #   - "80:3000"
    #   - "443:443"
    restart: always
    volumes:
      - certbot-webroot-evsoul:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-evsoul:/webroots/evsoul.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-webroot-evsoul:/webroots/evsoul.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
    # command: [nginx-debug, '-g', 'daemon off;']

volumes:
  certbot-webroot-evsoul:
  certbot-letsencrypt: